### ISSUE TITLE
bug: incorrect parse http/2

### ISSUE THREAD

**Issue by PandaWorker** [ShogunPanda/milo#9]
milo can't parse HTTP/2 and falls into error number 5
It can only parse according to the HTTP/{x}.{y}

OK
``` ts
const message = Buffer.from('HTTP/1.1 200 OK\r\nContent-Length: 3\r\n\r\nabc')
```

DONT PARSE
``` ts
const message = Buffer.from('HTTP/2 200 OK\r\nContent-Length: 3\r\n\r\nabc')
const message1 = Buffer.from('HTTP/3 200 OK\r\nContent-Length: 3\r\n\r\nabc')
```

**Comment by ShogunPanda** [comment]
I honestly dont't see the problem. Both HTTP2 and HTTP3 are binary protocols.
The only text based version of HTTP are 0.9, 1.0 and 1.1. Milo only supports the latter, as the former two are obsolete.
As Milo follows strict-only approach to the standard, it doesn't allow unknown protocol versions.

Closing this, feel free to comment more if you don't agree so we can eventually reopen.
